### ISSUE TITLE
How should I solve the following errors

### ISSUE THREAD

**Issue by KuangHao9** [t-34400/SimpleUnity3DWebView#1]
#00  pc 0x0000000006c93f74  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #01  pc 0x00000000072b2234  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #02  pc 0x00000000072b26dc  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #03  pc 0x000000000416eac8  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #04  pc 0x00000000043b948c  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #05  pc 0x00000000043b8ecc  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #06  pc 0x00000000043741a4  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #07  pc 0x0000000004372460  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #08  pc 0x0000000004372118  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #09  pc 0x000000000426118c  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #10  pc 0x000000000455f584  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #11  pc 0x000000000455fde0  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #12  pc 0x000000000456023c  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #13  pc 0x00000000045609d0  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #14  pc 0x000000000454df90  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #15  pc 0x0000000004558404  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #16  pc 0x00000000045400d4  /data/app/~~xFTod3I3iLP3oMScPNIzCw==/com.google.android.trichromelibrary_609921033-Ozh4Y1kvQoHHf1m390MELw==/base.apk!libmonochrome_64.so (BuildId: 6dece06e710240d87cd6e7fc6e892a5f04929d32)
  #17  pc 0x00000000000024b8  /system/lib64/libwebviewchromium_plat_support.so (android::(anonymous namespace)::draw_gl(int, void*, android::uirenderer::DrawGlInfo const&, android::uirenderer::WebViewOverlayData const&)+328)
  #18  pc 0x00000000002a5a94  /system/lib64/libhwui.so (android::uirenderer::WebViewFunctor::drawGl(android::uirenderer::DrawGlInfo const&)+196)
  #19  pc 0x00000000002788b0  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+1568)
  #20  pc 0x000000000030f0f4  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+116)
  #21  pc 0x0000000000680948  /system/lib64/libhwui.so (skgpu::v1::Device::drawDrawable(SkCanvas*, SkDrawable*, SkMatrix const*)+344)
  #22  pc 0x0000000000256828  /system/lib64/libhwui.so (android::uirenderer::$_37::__invoke(void const*, SkCanvas*, SkMatrix const&)+136)
  #23  pc 0x0000000000253930  /system/lib64/libhwui.so (android::uirenderer::DisplayListData::draw(SkCanvas*) const+128)
  #24  pc 0x000000000023cd88  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+1992)
  #25  pc 0x000000000023d4cc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+284)
  #26  pc 0x000000000030f0f4  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+116)
  #27  pc 0x0000000000253930  /system/lib64/libhwui.so (android::uirenderer::DisplayListData::draw(SkCanvas*) const+128)
  #28  pc 0x000000000023cd88  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+1992)
  #29  pc 0x000000000023d4cc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+284)
  #30  pc 0x000000000030f0f4  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+116)
  #31  pc 0x000000000027f41c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrameImpl(SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, SkCanvas*, SkMatrix const&)+508)
  #32  pc 0x000000000027ef94  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+596)
  #33  pc 0x000000000027ce14  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*)+484)
  #34  pc 0x0000000000283fcc  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+780)
  #35  pc 0x0000000000286a04  /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.c1671e787f244890c877724752face20)+884)
  #36  pc 0x00000000002769e4  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+580)
  #37  pc 0x0000000000296ea8  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+424)
  #38  pc 0x0000000000013440  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+416)
  #39  pc 0x00000000000c150c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #40  pc 0x0000000000054930  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by t-34400** [comment]
Hi, @KuangHao9.
Could you please provide more information or context about the issue?
