### ISSUE TITLE
Set cookie & Get cookie

### ISSUE THREAD

**Issue by wengyuan1110** [t-34400/SimpleUnity3DWebView#2]
Hi, I am trying to set and get cookie through EvaluateJavascript, but seems not working.

private string setCookie =
        "function setCookie(name, value, days)" +
        "{" +
        "    var expires = '';" +
        "    if (days)" +
        "    {" +
        "        var date = new Date();" +
        "        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));" +
        "        expires = '; expires=' + date.toUTCString();" +
        "    }" +
        "    document.cookie = name + '=' + (value || '') + expires + '; path=/';" +
        "}" +
        "setCookie('vc_token', '{token}', 1);";
webViewController?.EvaluateJavascript(setCookie );

**Comment by t-34400** [comment]
Hi, @wengyuan1110 ,

Thanks for reaching out about the issue.

I've investigated the problem and created a button that runs the same script as the issue. By pressing this button while monitoring the state of the WebView in the app via USB, I confirmed that the cookies are indeed set correctly.

If you have any more questions or need further help, feel free to ask!

### Unity
```c#
#nullable enable

using UnityEngine;
using WebView;

public class CookieSetter : MonoBehaviour
{
    private static string setCookie =
        "function setCookie(name, value, days)" +
        "{" +
        " var expires = '';" +
        " if (days)" +
        " {" +
        " var date = new Date();" +
        " date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));" +
        " expires = '; expires=' + date.toUTCString();" +
        " }" +
        " document.cookie = name + '=' + (value || '') + expires + '; path=/';" +
        "}" +
        "setCookie('vc_token', '{token}', 1);";

    [SerializeField] private WebViewControllerClient webViewController;

    public void SetCookie()
    {
        webViewController?.EvaluateJavascript(setCookie);
    }
}
```
![Screenshot_20240329_164803](https://github.com/t-34400/SimpleUnity3DWebView/assets/49368264/eb483cd3-13cb-4c85-8000-ca1a8a2875ce)

### Chrome Inspector (PC)
![image](https://github.com/t-34400/SimpleUnity3DWebView/assets/49368264/9bdf59f8-ac26-4878-9b9f-1162a6af8c47)
